### PR TITLE
Add description, manufacturingDate, expiryDate, & size fields in products.json file

### PR DESCRIPTION
**Pull request by minhajul-karim**
The error was occurring as description, manufacturingDate, expiryDate, & size are defined as required in the product schema but those fields were missing in the products.json file. I have added those fields to the products.json file and the seed is now working.

### CODE REVIEW

**Comment by foyzulkarim** [comment]
@minhajul-karim bhai, please remove the `package-lock.json` file from the PR.
Otherwise it looks awesome. Thanks

**Comment by minhajul-karim** [comment]
> @minhajul-karim bhai, please remove the `package-lock.json` file from the PR.
> Otherwise it looks awesome. Thanks

Bhaiya, deleted the package-lock.json file from /server

**Comment by foyzulkarim** [comment]
> > @minhajul-karim bhai, please remove the `package-lock.json` file from the PR.
> > Otherwise it looks awesome. Thanks
> 
> Bhaiya, deleted the package-lock.json file from /server

Brother, I requested to ignore from the PR, not to delete the file. Please check again.

**Comment by minhajul-karim** [comment]
Bhaiya, I've kept the package-lock.json as is when I created a new branch from feature/incorporate-antdpro. I'm relatively new to the open-source community. Your guidance will be highly appreciated. :)

**Comment by foyzulkarim** [comment]
> Bhaiya, I've kept the package-lock.json as is when I created a new branch from feature/incorporate-antdpro. I'm relatively new to the open-source community. Your guidance will be highly appreciated. :)

No worries brother. This is why I am requesting to change, no need to get stressed. :)

**Review by foyzulkarim — APPROVED** [review]
Nice work. :)

**Pull request merged**
